import './calibrate.css';
import { BASE_BOARD_SPOTS } from './base-board-setup.ts';
import { RESEARCH_LANES, RESEARCH_BOARD_SIZE } from './board-layout.ts';

type Mark={id:string;kind:'token'|'hotspot';asset:string;label:string;x:number;y:number;width:number;height:number;rotation:number};
type Stored=Partial<Mark>&{id:string;kind:'token'|'hotspot';x:number;y:number;radius?:number};
const BOARDS=[['main-bird','主板 · 普通','/assets/boards/main-bird.jpg'],['main-snake','主板 · 进阶','/assets/boards/main-snake.jpg'],['bird','研究轨 · Bird','/assets/boards/bird-board.jpg'],['snake','研究轨 · Snake','/assets/boards/snake-board.jpg'],['monkey','研究轨 · Monkey','/assets/boards/monkey-board.jpg'],['lizard','研究轨 · Lizard','/assets/boards/lizard-board.jpg'],['player-base','玩家板 · 基础','/assets/boards/player-base.jpg'],['leader-falconer','领袖 · Falconer','/assets/boards/leader-falconer.jpg'],['leader-explorer','领袖 · Explorer','/assets/boards/leader-explorer.jpg'],['leader-professor','领袖 · Professor','/assets/boards/leader-professor.jpg']] as const;
const ASSETS=[['archaeologist','考古学家','/assets/archaeologists-base-sprite.png'],['magnifying','放大镜','/assets/tokens-yellow-magnifying.png'],['journal','笔记本','/assets/tokens-yellow-journal.png'],['falcon','猎鹰','/assets/leader-falcon-token.png'],['snack-free','免费零食','/assets/leader-snack-free.png'],['snack-coin','金币零食','/assets/leader-snack-coin.png'],['snack-compass','罗盘零食','/assets/leader-snack-compass.png'],['coin','金币','/assets/resource-coin.png'],['compass','罗盘','/assets/resource-compass.png'],['tablet','石板','/assets/resource-tablet.png'],['arrowhead','箭头','/assets/resource-arrowhead.png'],['jewel','宝石','/assets/resource-jewel.png'],['idol-back','神像背面','/assets/idol-back.jpg'],['site-level1-back','一级地点背面','/assets/site-level1-back.jpg'],['site-level2-back','二级地点背面','/assets/site-level2-back.jpg'],['guardian-back','守卫背面','/assets/guardian-back.jpg'],['temple-2','神庙板块 2 分','/assets/temple-tile-2.png'],['temple-6','神庙板块 6 分','/assets/temple-tile-6.png'],['temple-11','神庙板块 11 分','/assets/temple-tile-11.png'],['suitcase','教授公文包','/assets/leader-professor-suitcase-alpha.png'],['research-bonus-1','研究奖励块（实体）','/assets/research-bonus-1.png'],['research-bonus-2','研究奖励块（实体）','/assets/research-bonus-2.png'],['research-bonus-3','研究奖励块（实体）','/assets/research-bonus-3.png'],['research-bonus-4','研究奖励块（实体）','/assets/research-bonus-4.png']] as const;
const app=document.querySelector<HTMLDivElement>('#app')!,key='arnak.board-calibrator.v2';let boardId=BOARDS[0][0],mode:'token'|'hotspot'='token',assetId=ASSETS[0][0],selected:string|undefined,dragging:string|undefined;let data:Record<string,Mark[]>={};try{const old=JSON.parse(localStorage.getItem(key)||localStorage.getItem('arnak.board-calibrator.v1')||'{}')as Record<string,Stored[]>;data=Object.fromEntries(Object.entries(old).map(([id,marks])=>[id,marks.map(m=>({...m,asset:m.asset??'',label:m.label??'',width:m.width??(m.radius??24)*2,height:m.height??(m.radius??24)*2,rotation:m.rotation??0}))]))as Record<string,Mark[]>}catch{}
const hotspot=(id:string,label:string,x:number,y:number,width=48,height=38):Mark=>({id,kind:'hotspot',asset:'',label,x,y,width,height,rotation:0});
const research=(id:keyof typeof RESEARCH_LANES)=>Object.entries(RESEARCH_LANES[id]).flatMap(([kind,points])=>points.map((p,n)=>hotspot(`${id}-${kind}-${n}`,`${kind}-${n}`,p.x/RESEARCH_BOARD_SIZE.width*100,p.y/RESEARCH_BOARD_SIZE.height*100,50,50)));
const mainBoardDefaults=(id:'main-bird'|'main-snake')=>BASE_BOARD_SPOTS.map(s=>{
  // Visual-QA measurements: discovered Level I tiles and their guardian
  // overlays occupy 150×150 source pixels; Level II occupies 160×160.
  const size=s.rewardCode?{width:42,height:34}:s.level===1?{width:150,height:150}:{width:160,height:160};
  return hotspot(`${id}-${s.id}`,s.id,s.left,s.top,size.width,size.height);
});
const defaults:Record<string,Mark[]>={'main-bird':mainBoardDefaults('main-bird'),'main-snake':mainBoardDefaults('main-snake'),bird:research('bird'),snake:research('snake'),monkey:research('monkey'),lizard:research('lizard'),'leader-explorer':[{id:'leader-explorer-snack-free',kind:'token',asset:'snack-free',label:'snack-free',x:60.31,y:16.77,width:90,height:90,rotation:0},{id:'leader-explorer-snack-coin',kind:'token',asset:'snack-coin',label:'snack-coin',x:60.31,y:49.39,width:90,height:90,rotation:0},{id:'leader-explorer-snack-compass',kind:'token',asset:'snack-compass',label:'snack-compass',x:60.24,y:82.62,width:90,height:90,rotation:0}]};for(const[id,marks]of Object.entries(defaults))if(!data[id]?.length)data[id]=marks;
const marks=()=>data[boardId]??[],asset=(id:string)=>ASSETS.find(a=>a[0]===id),board=()=>BOARDS.find(b=>b[0]===boardId)??BOARDS[0],persist=()=>localStorage.setItem(key,JSON.stringify(data));
const marker=(m:Mark)=>m.kind==='hotspot'?`<button class="mark hotspot ${m.id===selected?'selected':''}" style="--x:${m.x}%;--y:${m.y}%;--w:${m.width}px;--h:${m.height}px;--rot:${m.rotation}deg" data-mark="${m.id}" title="${m.label}"><span>${m.label||'互动'}</span></button>`:`<button class="mark token ${m.id===selected?'selected':''}" style="--x:${m.x}%;--y:${m.y}%;--w:${m.width}px;--h:${m.height}px;--rot:${m.rotation}deg" data-mark="${m.id}" title="${m.label}"><img src="${asset(m.asset)?.[2]||''}" alt="${m.label}"></button>`;
function render(){const b=board(),m=marks().find(x=>x.id===selected);app.innerHTML=`<main><header><strong>版图坐标采集器</strong><span>拖入贴图；互动点可与贴图重叠。坐标相对原图保存。</span><a href="/">游戏</a></header><section class="layout"><aside><label>版图<select data-board>${BOARDS.map(x=>`<option value="${x[0]}" ${x[0]===boardId?'selected':''}>${x[1]}</option>`).join('')}</select></label><div class="mode"><button data-mode="token" class="${mode==='token'?'active':''}">贴图 token</button><button data-mode="hotspot" class="${mode==='hotspot'?'active':''}">互动热区</button></div><p>互动热区：切换后点击空白处新增；拖动移动；右侧可调宽、高。</p><h2>可拖动贴图</h2><div class="palette">${ASSETS.map(x=>`<button draggable="true" data-asset="${x[0]}" class="${x[0]===assetId?'selected':''}"><img src="${x[2]}" alt=""><small>${x[1]}</small></button>`).join('')}</div></aside><section class="canvas-wrap"><div class="canvas" data-canvas><div class="image-plane"><img data-board-image src="${b[2]}" alt="${b[1]}">${marks().map(marker).join('')}</div></div></section><aside><h2>选中项</h2>${m?`<label>名称<input data-field="label" value="${m.label}"></label><label>宽度 px<input type="number" min="4" data-field="width" value="${m.width}"></label><label>高度 px<input type="number" min="4" data-field="height" value="${m.height}"></label><label>角度<input type="number" data-field="rotation" value="${m.rotation}"></label><code>x ${m.x}% · y ${m.y}%</code>${m.kind==='hotspot'?'<button data-test>测试点击动画</button>':''}<button data-delete>删除</button>`:'<p>选中/拖入标记后可命名、调整长宽和旋转。主板和研究轨已预录入现有互动点，可直接微调。</p>'}<h2>导出</h2><button data-copy>复制 JSON</button><button data-download>下载 JSON</button><textarea readonly>${JSON.stringify({version:2,boards:data},null,2)}</textarea></aside></section></main>`}
function point(e:MouseEvent|DragEvent){const r=app.querySelector<HTMLElement>('[data-board-image]')!.getBoundingClientRect();return{x:Math.round((e.clientX-r.left)/r.width*10000)/100,y:Math.round((e.clientY-r.top)/r.height*10000)/100}}
function place(e:MouseEvent|DragEvent,input:Partial<Mark>){const{x,y}=point(e),m:Mark={id:`${boardId}-${crypto.randomUUID()}`,kind:mode,asset:assetId,label:mode==='hotspot'?'interactive':assetId,x,y,width:48,height:40,rotation:0,...input};data[boardId]=[...marks(),m];selected=m.id;persist();render()}
function modify(id:string,c:Partial<Mark>){data[boardId]=marks().map(m=>m.id===id?{...m,...c}:m);persist();render()}function move(id:string,e:MouseEvent){const{x,y}=point(e);data[boardId]=marks().map(m=>m.id===id?{...m,x,y}:m);const el=app.querySelector<HTMLElement>(`[data-mark="${id}"]`);el?.style.setProperty('--x',`${x}%`);el?.style.setProperty('--y',`${y}%`)}function test(id:string){const el=app.querySelector<HTMLElement>(`[data-mark="${id}"]`);if(!el)return;el.classList.remove('testing');void el.offsetWidth;el.classList.add('testing');setTimeout(()=>el.classList.remove('testing'),850)}
app.addEventListener('change',e=>{const el=e.target as HTMLInputElement|HTMLSelectElement;if(el.matches('[data-board]')){boardId=el.value;selected=undefined;render();return}if(!selected||!el.dataset.field)return;const f=el.dataset.field;modify(selected,f==='label'?{label:el.value}:{[f]:Number(el.value)})});app.addEventListener('dragstart',e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-asset]')?.dataset.asset;if(id)e.dataTransfer?.setData('asset',id)});app.addEventListener('dragover',e=>{if((e.target as HTMLElement).closest('[data-canvas]'))e.preventDefault()});app.addEventListener('drop',e=>{if(!(e.target as HTMLElement).closest('[data-canvas]'))return;e.preventDefault();const id=e.dataTransfer?.getData('asset');if(id){assetId=id;place(e,{kind:'token',asset:id,label:id})}});app.addEventListener('click',async e=>{const t=e.target as HTMLElement,b=t.closest<HTMLElement>('button');if(!b&&t.closest('[data-canvas]'))return place(e,{});if(!b)return;if(b.dataset.mode){mode=b.dataset.mode as typeof mode;return render()}if(b.dataset.asset){assetId=b.dataset.asset;return render()}if(b.dataset.mark){selected=b.dataset.mark;return render()}if(b.dataset.test&&selected)return test(selected);if(b.dataset.delete!==undefined&&selected){data[boardId]=marks().filter(m=>m.id!==selected);selected=undefined;persist();return render()}if(b.dataset.copy)return navigator.clipboard.writeText(JSON.stringify({version:2,boards:data},null,2));if(b.dataset.download){const u=URL.createObjectURL(new Blob([JSON.stringify({version:2,boards:data},null,2)],{type:'application/json'})),a=Object.assign(document.createElement('a'),{href:u,download:'arnak-board-layout.json'});a.click();URL.revokeObjectURL(u)}});app.addEventListener('mousedown',e=>{const m=(e.target as HTMLElement).closest<HTMLElement>('[data-mark]');if(!m)return;e.preventDefault();selected=m.dataset.mark;dragging=selected;render()});app.addEventListener('mousemove',e=>{if(dragging&&e.buttons)move(dragging,e)});app.addEventListener('mouseup',()=>{if(dragging){persist();render()}dragging=undefined});persist();render();
