import { payTravel } from './travel-payment.ts';
import { payDiscardedHandCard } from './discard-cost.ts';
import { grantTemporaryTravel } from './action-window.ts';
import { resolveAssistantEffect } from './assistant-effects.ts';
import { defeatLizardTrackGuardian, lizardTrackGuardians } from './temples/lizard-state.ts';
import type { CardId, EngineContext, GameState, PlayerId, SpendableResource } from './types.ts';
const RESOURCES:SpendableResource[]=['coin','compass','tablet','arrowhead','jewel'];
function resolveGuardianDefeatRewards(state:GameState,playerId:PlayerId){for(const gain of state.players[playerId].guardianDefeatRewardsThisRound??[])for(const resource of RESOURCES){const amount=gain[resource]??0;if(!Number.isInteger(amount)||amount<0)throw new Error(`Invalid guardian trigger ${resource} gain`);state.players[playerId].resources[resource]+=amount;}}
function payGuardianCost(state:GameState,playerId:PlayerId,guardianId:string,context:EngineContext,paymentCardIds:CardId[],discardCardId?:CardId){const player=state.players[playerId],guardian=context.guardians?.[guardianId];if(!guardian)throw new Error(`Unknown guardian: ${guardianId}`);if(!guardian.cost)throw new Error(`Guardian cost is not verified: ${guardianId}`);for(const resource of RESOURCES){const amount=guardian.cost[resource]??0;if(!Number.isInteger(amount)||amount<0)throw new Error(`Invalid ${resource} guardian cost`);if(player.resources[resource]<amount)throw new Error(`Insufficient ${resource}`);}payDiscardedHandCard(state,playerId,guardian.cost.discardCard,discardCardId,'Guardian');payTravel(state,playerId,guardian.cost.travel??{},paymentCardIds,context,'Guardian travel');for(const resource of RESOURCES)player.resources[resource]-=guardian.cost[resource]??0;}
/** Standard main action: pay a guardian's printed resource and travel cost at a site occupied by your archaeologist. */
export function overcomeGuardian(state:GameState,playerId:PlayerId,siteId:string,context:EngineContext,paymentCardIds:CardId[]=[],discardCardId?:CardId){const player=state.players[playerId],site=state.sites[siteId];if(!player)throw new Error(`Unknown player: ${playerId}`);if(!site||site.occupiedBy!==playerId)throw new Error('Overcoming a guardian requires your archaeologist at the site');const guardianId=site.guardian;if(!guardianId)throw new Error('There is no guardian at this site');payGuardianCost(state,playerId,guardianId,context,paymentCardIds,discardCardId);delete site.guardian;player.defeatedGuardians.push(guardianId);resolveGuardianDefeatRewards(state,playerId);}
/** Standard main action against the revealed guardian printed on the Lizard research track. */
export function overcomeLizardTrackGuardian(state:GameState,playerId:PlayerId,context:EngineContext,paymentCardIds:CardId[]=[],discardCardId?:CardId){const player=state.players[playerId];if(!player)throw new Error(`Unknown player: ${playerId}`);const guardian=lizardTrackGuardians(state).find(value=>!value.defeated);if(!guardian||!guardian.revealed)throw new Error('No revealed Lizard track guardian is available');if(state.research.magnifyingNode[playerId]!==guardian.nodeId)throw new Error('Overcoming the Lizard guardian requires your magnifying glass at its row');payGuardianCost(state,playerId,guardian.id,context,paymentCardIds,discardCardId);defeatLizardTrackGuardian(state,guardian.id);player.defeatedGuardians.push(guardian.id);resolveGuardianDefeatRewards(state,playerId);}
/** Use a collected guardian's printed boon once. It is intentionally separate from defeating it. */
export function activateGuardianBoon(state:GameState,playerId:PlayerId,guardianId:string,context:EngineContext):GameState{const player=state.players[playerId];if(!player)throw new Error(`Unknown player: ${playerId}`);if(!player.defeatedGuardians.includes(guardianId))throw new Error('Guardian boon requires a defeated guardian you own');if(player.usedGuardianBoons.includes(guardianId))throw new Error('Guardian boon has already been used');const boon=context.guardians?.[guardianId]?.boon;if(!boon)throw new Error(`Guardian boon is not verified: ${guardianId}`);player.usedGuardianBoons.push(guardianId);if(boon.type==='GAIN_TRAVEL')return grantTemporaryTravel(state,playerId,boon.travel);return resolveAssistantEffect(state,playerId,guardianId,boon,'guardian');}
